name: 'Build (iOS)'

on: [push, pull_request]

jobs:
  build-iossimulator:
    name: "iOS Simulator Build"
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@main

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: 'Build'
        run: |
          xcodebuild -project Xcode/SDL/SDL.xcodeproj -scheme SDL3 -configuration Release -destination 'platform=iOS Simulator,name=iPhone 15' CONFIGURATION_BUILD_DIR=$PWD/Build
      - name: "Create archive"
        run: zip -r "ios.zip" .
      - uses: actions/upload-artifact@v4
        with:
          name: iOS Simulator
          path: ios.zip
