name: 'Build (iOS)'

on: [push, pull_request]

jobs:
  build-iossimulator:
    name: "iOS Simulator Build"
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@main

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: "Build"
        run:
          cd build-scripts && sh buildios.sh
