name: 'Build (iOS)'

on: [push, pull_request]

jobs:
  build-iossimulator:
    name: "iOS Simulator Build"
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@main

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: 'CMake (configure + build) iOS'
        run: |
          cmake               \
              -DCMAKE_SYSTEM_NAME=iOS                                       \
              -DCMAKE_OSX_ARCHITECTURES="arm64"                             \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=9.0                             \
              -Werror=dev                                                   \
              -B build_ios
          cmake --build build_ios --config Release --verbose
